_name_or_path:
    value: geodesic-research/sfm-sft_dolci_think_unfiltered
_wandb:
    value:
        cli_version: 0.23.1
        e:
            5pqhmreyzyc0jjssj05fnz8dgrsry0in:
                args:
                    - --output_dir
                    - ./outputs/dpo-think-8gpu
                    - --hub_model_id
                    - camgeodesic/sfm-think-DPO
                    - --push_to_hub
                    - "true"
                    - --deepspeed
                    - ds_config.json
                    - --beta
                    - "5.0"
                    - --learning_rate
                    - "1e-6"
                    - --lr_scheduler_type
                    - linear
                    - --warmup_ratio
                    - "0.1"
                    - --num_train_epochs
                    - "1"
                    - --per_device_train_batch_size
                    - "16"
                    - --gradient_accumulation_steps
                    - "1"
                    - --max_length
                    - "4096"
                    - --max_prompt_length
                    - "4096"
                    - --logging_steps
                    - "10"
                    - --save_steps
                    - "1000"
                    - --bf16
                    - "true"
                    - --gradient_checkpointing
                    - "true"
                    - --report_to
                    - wandb
                    - --run_name
                    - dpo-think-8gpu-olmo3
                    - --dataloader_num_workers
                    - "4"
                    - --use_liger_kernel
                    - "false"
                    - --max_samples
                    - "100000"
                codePath: train_dpo.py
                codePathLocal: train_dpo.py
                cpu_count: 220
                cpu_count_logical: 220
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "6833690677248"
                        used: "1483681931264"
                email: cam@meridiancambridge.org
                executable: /home/ctice/sfm-post-training/.venv/bin/python3
                git:
                    commit: 0682670b4957e6779bdde2e510a01a8739c1d349
                    remote: https://github.com/MeridianResearch/sfm-post-training
                gpu: NVIDIA B200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-59d75fb6-f4e3-bbb1-4f90-afd5eacacc64
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-0ae0db50-2f54-b355-b286-174679c3064e
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-25ddd7a6-a6ff-57bb-84c5-f14b8bec8c7d
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-18c48fa8-49ae-6fac-93b7-691b6347a5c4
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-4a95a812-a511-b9f7-dd4e-1769a67b0d80
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-37cfea96-cc94-0f24-99b9-10d6a8810393
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-469b3fd9-d556-c6d0-306b-2fb1665a772b
                    - architecture: Blackwell
                      cudaCores: 18944
                      memoryTotal: "192265846784"
                      name: NVIDIA B200
                      uuid: GPU-749c664c-cce8-97ce-19a1-87bc84cc0276
                host: ci1
                memory:
                    total: "2705617235968"
                os: Linux-5.15.0-161-generic-x86_64-with-glibc2.35
                program: /home/ctice/sfm-post-training/train_dpo.py
                python: CPython 3.10.12
                root: /home/ctice/sfm-post-training
                slurm:
                    cluster_name: civo-b200
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "64"
                    cpus_per_task: "64"
                    gpus_on_node: "8"
                    gtids: "0"
                    job_account: geodesic-research
                    job_cpus_per_node: "64"
                    job_end_time: "1765625873"
                    job_gid: "1005"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "166"
                    job_name: dpo-train-8gpu
                    job_nodelist: localhost
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1765604273"
                    job_uid: "1003"
                    job_user: ctice
                    jobid: "166"
                    localid: "0"
                    mem_per_node: "921600"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: localhost
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/ctice/sfm-post-training
                    submit_host: ci1
                    task_pid: "1005231"
                    tasks_per_node: "1"
                    topology_addr: localhost
                    topology_addr_pattern: node
                    tres_per_task: cpu=64
                startedAt: "2025-12-13T05:57:15.338098Z"
                writerId: 5pqhmreyzyc0jjssj05fnz8dgrsry0in
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
            "3":
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.10.12
            "5": 0.23.1
            "6": 4.57.3
            "9":
                "1": transformers_trainer
            "12": 0.23.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - GPTNeoXForCausalLM
attention_bias:
    value: true
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
base_model_attribute_name:
    value: model
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
beta:
    value: 5
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 0
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: 0.1
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_num_proc:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: ds_config.json
disable_dropout:
    value: true
disable_tqdm:
    value: false
discopop_tau:
    value: 0.05
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 0
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
f_alpha_divergence_coef:
    value: 1
f_divergence_type:
    value: reverse_kl
finetuning_task:
    value: null
force_use_ref_model:
    value: false
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generate_during_eval:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout:
    value: 0
hidden_size:
    value: 4096
hub_always_push:
    value: false
hub_model_id:
    value: camgeodesic/sfm-think-DPO
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 16384
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_pad_token_id:
    value: -100
label_smoothing:
    value: 0
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_eps:
    value: 1e-05
ld_alpha:
    value: null
learning_rate:
    value: 1e-06
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./outputs/dpo-think-8gpu/runs/Dec13_05-38-03_ci1
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: sigmoid
loss_weights:
    value: null
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
max_completion_length:
    value: null
max_grad_norm:
    value: 1
max_length:
    value: 4096
max_position_embeddings:
    value: 16384
max_prompt_length:
    value: 4096
max_steps:
    value: -1
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 6856253440
model_adapter_name:
    value: null
model_init_kwargs:
    value: null
model_type:
    value: gpt_neox
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./outputs/dpo-think-8gpu
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 0
padding_free:
    value: false
parallelism_config:
    value: null
partial_rotary_factor:
    value: 0.25
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 16
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
precompute_ref_batch_size:
    value: null
precompute_ref_log_probs:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: true
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
ref_adapter_name:
    value: null
ref_model_init_kwargs:
    value: null
ref_model_mixup_alpha:
    value: 0.6
ref_model_sync_steps:
    value: 512
reference_free:
    value: false
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rope_scaling:
    value: null
rope_theta:
    value: 10000
rotary_emb_base:
    value: 10000
rotary_pct:
    value: 0.25
rpo_alpha:
    value: null
run_name:
    value: dpo-think-8gpu-olmo3
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
sync_ref_model:
    value: false
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
tools:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.3
truncation_mode:
    value: keep_end
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_liger_loss:
    value: null
use_logits_to_keep:
    value: false
use_mps_device:
    value: false
use_parallel_residual:
    value: true
use_weighting:
    value: false
vocab_size:
    value: 50304
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0
